### ISSUE TITLE
不完善的插件!你们北京人屁眼长头上

### ISSUE THREAD

**Issue by jiayouzl** [Germey/LaravelGeetest#11]
中国人还整个自动翻译成英文不说,各种不全,你们北京人是不是都屁眼长头上!

英文不好就别整,什么破英文的文档?各种不全,按你的步骤能显示验证码?SB!

**Comment by Germey** [comment]
哥们你真逗，有本事自己写咯，我开源的收你钱了么？自己搞不懂原理还来着喷，别人怎么就没事？

**Comment by lxin87** [comment]
逛github这么久了，这次真是长见识了
