### ISSUE TITLE
请支持极验的3.0验证码

### ISSUE THREAD

**Issue by mr-cn** [Germey/LaravelGeetest#12]
极验现在出了新版本的验证码，点击一下按钮就识别完了，用户体验很好
希望可以集成一下，感谢。

BTW,极验那边好像是说免费用户不支持HTTPS？不知可否解决？

**Comment by Germey** [comment]
您好，刚从国外回来看到，请问现在的版本是不能用了吗？
我会尽快集成一下，https问题这个不太清楚，我后面统一排查一下更新一下。感谢支持！

**Comment by mr-cn** [comment]
极验最近发布了新版本的验证，与以前的“滑动式”验证相比现在只需要点击就可以了，用户体验更棒了。
不影响原来的使用。
其实我更加在意HTTPS的问题……

**Comment by SimonFuu** [comment]
等一个3.0。。。-，-

**Comment by yangfan21** [comment]
同求一个支持3.0的    我在packagist 上面有看到一个 https://packagist.org/packages/gee-team/gt-php-sdk   但是根本就没有使用文档

**Comment by Germey** [comment]
@yangfan21 @SimonFuu 您好，最近在赶一个项目，还没时间集成，https://github.com/jormin/laravel-geetest 我看到有这样到一个Package，您看看可以使用吗？

**Comment by yangfan21** [comment]
非常感谢 我去试一下

**Comment by Germey** [comment]
已支持～
