### ISSUE TITLE
ajax服务端异常

### ISSUE THREAD

**Issue by mr-cn** [Germey/LaravelGeetest#14]
看到3.0的更新，升级完毕之后，发现验证码无法加载，F12看到JS报错如下：
```
Uncaught Error: 初始化gt传参错误
    at new c (static.geetest.com/static/js/geetest.0.0.0.js:1)
    at new d (static.geetest.com/static/js/geetest.0.0.0.js:1)
    at init (gt.js:255)
    at gt.js:275
    at gt.js:167
    at gt.js:109
```
ajax返回的数据为`"success":0,"gt":null`，因为gt为null所以传参错误。
检查了API信息正确，同一机器使用2.0旧版正常。

**Comment by Germey** [comment]
感谢您的测试，昨天我刚刚赶出来，这版SDK改了不少，我重新排查一下错误，谢谢～

**Comment by Germey** [comment]
你好，我自己测试了一下，确实没有问题，可以正常显示。

**Comment by mr-cn** [comment]
@Germey 
既然你正常显示，说明扩展并没有问题，这个Issue就没有意义了。
可能是我升级时有东西没有调整吧，我自己再看看吧。
anyway，麻烦了。
