### ISSUE TITLE
在laravel 5.1中不能用。

### ISSUE THREAD

**Issue by icemanpro** [Germey/LaravelGeetest#16]
运行php artisan route:list 报 Call to undefined method Germey\Geetest\GeetestController::getMiddleware()  

需要将germey/geetest/src/GeetestController.php 改为
```php
<?php

namespace Germey\Geetest;


use Illuminate\Routing\Controller;

class GeetestController extends Controller
{
	use GeetestCaptcha;
}
```

同时，解决  http://homestead.app/auth/geetest?t=1473062275344 500 (Internal Server Error)

**Comment by Germey** [comment]
非常抱歉一直没有处理，现已修复，深表感谢！
