### ISSUE TITLE
在 Service 端中的校验失败的问题

### ISSUE THREAD

**Issue by Seaony** [Germey/LaravelGeetest#19]
我在我的 `Project` 中使用了您的包，但是我在进行服务端校验时遇到了一点小问题，我使用了 `Ajax` 请求来提交我的 `Form` 表单，但是一直得到验证失败的返回。我查看了一下源码，觉得可能与 `Session` 相关，于是我在我的控制器里启用了 `Session` （起先是在 `Api` 路由中进行的校验）,但是得到的结果还是校验失败，查看了一下官方的SDK代码，在离线校验时是使用的MD5值对比，我不知道出了什么问题，你可以给我一点建议吗？

Client Code

```javascript
            $.ajax({
                cache: false,
                type: "POST",
                url: '{{ route('auth.send_verify_code') }}',
                data: $('#auth-register').serialize(),
                async: false,
                error: function (respond) {
                    return failedMessage('获取验证码失败，请刷新重试！')
                },

                success: function (respond) {
                    if (!respond.status) {
                        return failedMessage(respond.msg)
                    }
                }

            })
```

Service Code

```php
    public function checkMobileIsAllow($mobile = null)
    {
        $validator = Validator::make(
            ['mobile' => $mobile],
            ['mobile' => 'required|digits:11|unique:member|geetest'],
            ['geetest' => config('geetest.server_fail_alert')]
        );

        if ($validator->fails()) {
            throw new ValidatorException($validator->errors()->first());
        }

        return true;
    }
```

**Comment by Germey** [comment]
验证规则貌似是：`'geetest_challenge' => 'geetest'` 吧？

**Comment by Seaony** [comment]
使用 `geetest_challenge` 这个字段也尝试过，也是验证失败，后来采用 `mobile` 的原因是不想多单独写一层

**Comment by dezhaohe** [comment]
我这几天也碰过宕机模式下验证不通过的问题。通过对比官网的Demo代码，找到了原因了。germey的GeetestLib.php有一断代码，少了一句：
private function failbackProcess()
	{
		$rnd1 = md5(rand(0, 100));
		$rnd2 = md5(rand(0, 100));
		$challenge = $rnd1 . substr($rnd2, 0, 2);
		$result = [
			'success' => 0,
			'gt' => $this->captcha_id,
			'challenge' => $challenge,
			'new_captcha' => 1   ---------> 少了这句

		];
		$this->response = $result;
	}
 官网资料http://docs.geetest.com/install/client/web-front/里说明：
new_captcha: 布尔类型。宕机情况下使用，表示验证是 3.0 还是 2.0，3.0 的 sdk 该字段为 true
如果没有设置这个值，默认走2.0的验证，导致数据错误。

发现过程：
修改DNS，使得api.geetest.com 指向本机，模拟极验宕机模式的逻辑时发现前端提交到后台的数据类似这样：     geetest_challenge:a684eceee76fc522773286a895bc84363c  geetest_validate:2e256c_22447c_2eeee96   geetest_seccode:2e256c_22447c_2eeee96|jordan  ，但后台验证代码是public function fail_validate($challenge, $validate, $seccode) {
        if(md5($challenge) == $validate){
            return 1;
        }else{
            return 0;
        }
    }
geetest_validate获取的值明显有问题，故怀疑参数有误。

**Comment by Germey** [comment]
你好，现已修复，请更新 3.0.4 版本试用~
