### ISSUE TITLE
在laravel5.3上使用报错

### ISSUE THREAD

**Issue by zhaoyang017** [Germey/LaravelGeetest#2]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'class，' in /var/www/laravel/config/app.php:183
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(60): require()
#1 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(38): Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\Foundation\Application), Object(Illuminate\Config\Repository))
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(251): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(109): Illuminate\Foundation\Console\Kernel->bootstra in /var/www/laravel/config/app.php on line 183

**Comment by Germey** [comment]
感觉似乎不是Geetest的错误？你那边后来解决了吗？

**Comment by zhaoyang017** [comment]
@Germey 是我自己的问题，现在解决了，不过出现了新的问题，一直提示正在加载验证码
jquery.min.js:4 GET http://homestead.app/auth/geetest?t=1473062275344 500 (Internal Server Error)

**Comment by zhaoyang017** [comment]
而且验证码图片不显示

**Comment by Germey** [comment]
报500错误的话，再把storage赋予777权限，应该就会有错误提示了
