### ISSUE TITLE
当用户名或密码校验失败后如何对geetest进行reset？

### ISSUE THREAD

**Issue by Bantes** [Germey/LaravelGeetest#21]
ajax进行登录的，除了重刷当前页怎么对geetest进行reset?
官方文档是captchaObj.onSuccess中进行用户登录ajax操作，然后如果登录失败的话进行captchaObj.reset()操作。

那这样是不是要重写一份geetest.blade.php

**Comment by Germey** [comment]
是的，目前的版本没有对这个做处理，如果要改的话可以复写一下这个blade。后面有时间我会更新一下这个问题。非常感谢你的建议！

**Comment by awei007** [comment]
@Bantes 大哥，你是怎么处理的呢？我这边captchaObj.reset()没反应。
