### ISSUE TITLE
功能正常但一直显示"正在加载验证码..."

### ISSUE THREAD

**Issue by lxin87** [Germey/LaravelGeetest#30]
如图:

![image](https://user-images.githubusercontent.com/1697243/45864595-0b37d380-bdad-11e8-96fa-d6d1cb276260.png)

功能没有问题，只是多了一个显示，感觉有些不舒服，我使用的`laravel5.6`，同一个项目，只是前后台是不同表实现的认证，所以有`两个登陆界面`，后台是我自己找的基于`booterstrap`的后台模板，那个界面没有问题，因为bootstrap里已经有一个`.hide`，而且样式是`display:none !important`,但`laravel`自带的认证登陆页面上没有。查看了下样式，.hide类是加上去了，但是`display:none`没有生效，也就是你在`geetest.blade.php`模板里设置的样式没有起作用。

后来做了下修改，如下:
```php
captchaObj.onReady(function() {
      $("#wait-{{ $captchaid }}")[0].className = "hide";
 });

//change to 

captchaObj.onReady(function() {
       $("#wait-{{ $captchaid }}").hide();
});

```

**Comment by sriniprabu** [comment]
Running 

$ php artisan vendor:publish --tag=geetest

Doesn't create resources/views/vendor/geetest or geetest.blade.php in laravel 5.8 Is there any solution or chance of updating the library with support for laravel 5.8 and Vuejs
