### ISSUE TITLE
Configuration is not working

### ISSUE THREAD

**Issue by raulgonve** [Germey/LaravelGeetest#32]
Hello,

php artisan vendor:publish --tag=geetest, this command is not doing what supposed to do and the class is not recognize at views.

Regards!

**Comment by esvalsecchi** [comment]
I think i have a similar problem, after following all steps i can not find config/geetest.php, when I run the view I am having the next error: Class 'Geetest' not found (View: C:\xampp\htdocs\chikyjump\resources\views\index.blade.php)
