### ISSUE TITLE
Support laravel 6

### ISSUE THREAD

**Issue by vladyslavstartsev** [Germey/LaravelGeetest#33]
Hi! There is no laravel 6 support at the moment, can you please add it?

**Comment by Germey** [comment]
Sorry, I've not use PHP for a long time, so this package is no longer maintained. Could you please contribute to it? Thanks very much!

**Comment by vladyslavstartsev** [comment]
Can I get right to manage it?

**Comment by Germey** [comment]
@vladyslavstartsev I've added you as a collabrator in this repo, thanks for your contribution.
