### ISSUE TITLE
Usage in the doc not working

### ISSUE THREAD

**Issue by hudson6666** [Germey/LaravelGeetest#9]
I supposed that the usage in the readme was wrong.

``` PHP
  /**
   * @param Request $request
   */
  public function postValidate(Request $request)
  {
    $result = $this->validate($request, [
      'geetest_challenge' => 'geetest',
    ], [
      'geetest' => config('geetest.server_fail_alert')
    ]);
    if ($result) {
      return 'success';
    }
  }
```

A prompt will be shown by phpstorm that function validate is a **void function**. And this code did fail to work, it returns false even if I properly dealed with the captcha.

In fact, in laravel doc,

> The validate method accepts an incoming HTTP request and a set of validation rules. If the validation rules pass, your code will keep executing normally; however, if validation fails, an exception will be thrown and the proper error response will automatically be sent back to the user. In the case of a traditional HTTP request, a redirect response will be generated, while a JSON response will be sent for AJAX requests.

Indeed I cannot found a usage like that.

I suppose, by any chance, a proper use should be like this,
``` PHP
    /**
     * @param Request $request
     * @return bool
     */
    private function geetestValidate(Request $request)
    {
        $this->validate($request, [
            'geetest_challenge' => 'geetest',
        ], [
            'geetest' => config('geetest.server_fail_alert')
        ]);
        return true;
    }
```
And this did work for me.

Regards.

**Comment by Germey** [comment]
Thanks, I've updated the document.
